import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../../config/constants';

export const styles = StyleSheet.create({
  scroll: { paddingBottom: 24 },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 56 : 48,
    paddingBottom: 16,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  backBtn: { width: 40, height: 40, justifyContent: 'center' },
  backBtnText: { fontSize: 26, color: '#333' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#1A1A2E' },

  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: '#1A1A2E', marginBottom: 4 },

  addressContainer: { flexDirection: 'row', marginTop: 10 },
  addressLine: { width: 20, alignItems: 'center', marginRight: 14, paddingTop: 28 },
  dot: { width: 10, height: 10, borderRadius: 5 },
  vertLine: { flex: 1, width: 2, backgroundColor: '#E0E0E0', marginVertical: 4 },

  inputError: { borderColor: '#E63946' },
  fieldError: { color: '#E63946', fontSize: 11, marginTop: 4 },

  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#333',
    backgroundColor: '#FAFAFA',
  },
  inputMt: { marginTop: 10 },

  pkgTypeCard: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginRight: 10,
    alignItems: 'center',
    backgroundColor: '#fff',
    minWidth: 82,
  },
  pkgTypeCardSelected: { backgroundColor: COLORS.blue, borderColor: COLORS.blue },
  pkgTypeIcon: { fontSize: 24 },
  pkgTypeLabel: { fontSize: 11, color: '#666', marginTop: 5, fontWeight: '500', textAlign: 'center' },
  pkgTypeLabelSelected: { color: '#fff' },

  vehicleRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
  vehicleCard: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    alignItems: 'center',
    paddingVertical: 16,
    backgroundColor: '#fff',
  },
  vehicleCardSelected: { borderColor: COLORS.blue, backgroundColor: COLORS.blueLight },
  vehicleIcon: { fontSize: 30 },
  vehicleLabel: { fontSize: 12, color: '#666', marginTop: 6, fontWeight: '500' },
  vehicleLabelSelected: { color: COLORS.blue, fontWeight: '700' },
  vehicleLimitText: { fontSize: 11, color: COLORS.warning, marginTop: 6 },

  priceRow: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  priceInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 14,
    fontSize: 24,
    fontWeight: '700',
    color: '#1A1A2E',
    textAlign: 'center',
    backgroundColor: '#FAFAFA',
  },
  currency: { fontSize: 18, fontWeight: '700', color: '#666', marginLeft: 14 },

  submitBtn: {
    backgroundColor: COLORS.blue,
    borderRadius: 16,
    padding: 18,
    marginHorizontal: 16,
    marginTop: 20,
    alignItems: 'center',
    shadowColor: COLORS.blue,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  submitBtnDisabled: { opacity: 0.5 },
  submitBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
});
