import { StyleSheet } from 'react-native';
import { Colors, Spacing, Radius, FontSize } from '../../../config/theme';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: Colors.bgDark },
  container: { flex: 1, backgroundColor: Colors.bgDark },
  scrollContent: { paddingBottom: 32 },

  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing.md,
  },
  greeting: { fontSize: FontSize.sm, color: Colors.textSecondary },
  agenceName: { fontSize: FontSize.xl, fontWeight: '800', color: Colors.textPrimary },
  topBarRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  notifBtn: { position: 'relative', padding: Spacing.xs },
  notifIcon: { fontSize: 22 },
  notifBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.error,
  },
  avatarBtn: {
    width: 40,
    height: 40,
    borderRadius: Radius.full,
    backgroundColor: Colors.primaryGhost,
    borderWidth: 1.5,
    borderColor: Colors.borderActive,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: { color: Colors.primary, fontWeight: '700', fontSize: FontSize.sm },

  statsScroll: { marginBottom: Spacing.md },
  statsContent: { paddingHorizontal: Spacing.lg, gap: 10 },

  newCommandeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    marginHorizontal: Spacing.lg,
    borderRadius: Radius.md,
    height: 52,
    gap: 8,
    marginBottom: Spacing.lg,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  newCommandeIcon: { color: '#fff', fontSize: 22, fontWeight: '300' },
  newCommandeText: { color: '#fff', fontSize: FontSize.lg, fontWeight: '700' },

  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  voirTout: { fontSize: FontSize.sm, color: Colors.primary, fontWeight: '600' },
  sectionTitle: { fontSize: FontSize.lg, fontWeight: '700', color: Colors.textPrimary },
  sectionCount: {
    backgroundColor: Colors.bgElevated,
    color: Colors.textSecondary,
    fontSize: FontSize.xs,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.border,
  },

  filtersScroll: { marginBottom: Spacing.md },
  filtersContent: { paddingHorizontal: Spacing.lg, gap: 8 },
  filterChip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs + 2,
    borderRadius: Radius.full,
    backgroundColor: Colors.bgCard,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  filterChipActive: {
    backgroundColor: Colors.primaryGhost,
    borderColor: Colors.borderActive,
  },
  filterText: { fontSize: FontSize.sm, color: Colors.textSecondary, fontWeight: '600' },
  filterTextActive: { color: Colors.primary },

  commandesList: { paddingHorizontal: Spacing.lg, gap: 12 },

  emptyState: { alignItems: 'center', paddingVertical: 40 },
  emptyIcon:  { fontSize: 52, marginBottom: 12 },
  emptyText:  { fontSize: FontSize.sm, color: Colors.textSecondary, marginBottom: 12 },
  emptyLink:  { fontSize: FontSize.sm, color: Colors.primary, fontWeight: '700' },
});
