import { StyleSheet } from 'react-native';
import { COLORS } from '../../../config/constants';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  backBtn: { width: 40, height: 40, justifyContent: 'center' },
  backBtnText: { fontSize: 26, color: '#333' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#1A1A2E' },
  orderBadge: {
    backgroundColor: COLORS.blueLight,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  orderBadgeText: { color: COLORS.blue, fontWeight: '700', fontSize: 13 },

  scroll: { padding: 16 },

  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  cardTitle: { fontSize: 14, fontWeight: '700', color: '#1A1A2E', marginBottom: 14 },

  driverRow: { flexDirection: 'row', alignItems: 'center' },
  driverAvatar: { fontSize: 48, marginRight: 14 },
  driverInfo: { flex: 1 },
  driverName: { fontSize: 17, fontWeight: '700', color: '#1A1A2E' },
  driverRating: { fontSize: 13, color: '#666', marginTop: 3 },
  assignedBadge: {
    backgroundColor: '#EAFAF1',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  assignedBadgeText: { color: COLORS.success, fontWeight: '700', fontSize: 11 },

  routeContainer: { flexDirection: 'row' },
  connector: {
    width: 20,
    alignItems: 'center',
    marginRight: 14,
    paddingTop: 4,
  },
  connDot: { width: 10, height: 10, borderRadius: 5 },
  connLine: { flex: 1, width: 2, backgroundColor: '#E0E0E0', marginVertical: 4 },
  routeItem: {},
  routeLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#BDBDBD',
    letterSpacing: 1,
    marginBottom: 3,
  },
  routeAddress: { fontSize: 14, fontWeight: '600', color: '#1A1A2E', lineHeight: 20 },
  distanceRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F5',
    paddingLeft: 34,
  },
  distanceText: { fontSize: 14, color: '#555', fontWeight: '600' },

  mapsBtn: {
    backgroundColor: COLORS.blue,
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: COLORS.blue,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  mapsBtnDisabled: { backgroundColor: '#BDBDBD', shadowOpacity: 0 },
  mapsBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },

  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  detailItem: {
    backgroundColor: COLORS.bg,
    borderRadius: 10,
    padding: 10,
    minWidth: '45%',
    flex: 1,
  },
  detailLabel: { fontSize: 10, color: '#999', fontWeight: '700', letterSpacing: 0.5, marginBottom: 4 },
  detailValue: { fontSize: 13, color: '#1A1A2E', fontWeight: '600' },

  clientRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F5',
  },
  clientName: { fontSize: 14, color: '#333', fontWeight: '600' },
  clientPhone: { fontSize: 13, color: COLORS.blue, fontWeight: '600' },
});
