export const MOCK_COMMANDES_AGENCE = [
  {
    id: '1',
    pickupAdresse: 'Maarif, Casablanca',
    depotAdresse: 'Hay Hassani, Casablanca',
    description: 'Colis électronique fragile',
    prix: 45,
    vehiculeType: 'moto',
    statut: 'en_route',
    livreur: 'Youssef B.',
    distance: 6.2,
    createdAt: '2025-02-25T08:30:00',
  },
  {
    id: '2',
    pickupAdresse: 'Guéliz, Marrakech',
    depotAdresse: 'Hivernage, Marrakech',
    description: 'Documents importants',
    prix: 30,
    vehiculeType: 'moto',
    statut: 'en_attente',
    livreur: null,
    distance: 3.1,
    createdAt: '2025-02-25T09:00:00',
  },
  {
    id: '3',
    pickupAdresse: 'Agdal, Rabat',
    depotAdresse: 'Océan, Rabat',
    description: 'Vêtements x3 sacs',
    prix: 60,
    vehiculeType: 'voiture',
    statut: 'livree',
    livreur: 'Amine K.',
    distance: 4.8,
    createdAt: '2025-02-24T14:00:00',
  },
  {
    id: '4',
    pickupAdresse: 'Ain Diab, Casablanca',
    depotAdresse: 'Anfa, Casablanca',
    description: 'Matériaux de bureau',
    prix: 90,
    vehiculeType: 'camionnette',
    statut: 'acceptee',
    livreur: 'Khalid M.',
    distance: 2.3,
    createdAt: '2025-02-25T07:15:00',
  },
];

export const MOCK_COMMANDES_LIVREUR = [
  {
    id: '10',
    pickupAdresse: 'Maarif, Casablanca',
    depotAdresse: 'Sidi Maarouf, Casablanca',
    description: 'Téléphone portable',
    prix: 55,
    vehiculeType: 'moto',
    distance: 7.4,
    tempsEstime: '25 min',
    agence: 'Express Maroc',
  },
  {
    id: '11',
    pickupAdresse: 'Ain Sebaa, Casablanca',
    depotAdresse: 'Bernoussi, Casablanca',
    description: 'Colis alimentaire',
    prix: 35,
    vehiculeType: 'moto',
    distance: 3.2,
    tempsEstime: '12 min',
    agence: 'QuickDel',
  },
  {
    id: '12',
    pickupAdresse: 'Oulfa, Casablanca',
    depotAdresse: 'Lissasfa, Casablanca',
    description: 'Médicaments urgents',
    prix: 70,
    vehiculeType: 'moto',
    distance: 5.1,
    tempsEstime: '18 min',
    agence: 'MediExpress',
  },
];

export const MOCK_STATS_AGENCE = {
  totalCommandes: 128,
  enCours: 3,
  livrees: 112,
  enAttente: 13,
  gainsMois: 4850,
};

export const MOCK_STATS_LIVREUR = {
  commandesAujourdhui: 7,
  gainsAujourdhui: 315,
  gainsSemaine: 1640,
  note: 4.8,
  totalLivraisons: 342,
};
